### ISSUE TITLE
Subcortical cerebral atrophy includes both Cerebral white matter atrophy and Atrophy/Degeneration involving the caudate nucleus

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#6817] opened 2021-04-06 13:05 UTC
**HPO term**
Subcortical cerebral atrophy HP:0012157

**Suggested revision and reasons**
Subcortical atrophy can involve grey or white matter. Hence I propose placing the following terms as its children:

Cerebral white matter atrophy HP:0012762
Atrophy/Degeneration involving the caudate nucleus HP:0007374

**Comment by pnrobinson** [comment] 2021-04-25 23:27
The issue is that a subclass implies "always" -- cerebral WM atrophy is not always subcortical, I think. I am less sure about the caudate. If it is only "sometimes", then we should not make this link @DLewisSmith

**Comment by pnrobinson** [comment] 2021-05-09 12:48
I think we should not make these links, I will close this term, please reopen if you feel this is wrong.

**Closed by pnrobinson** 2021-05-09 12:48 UTC
Labels: hpo-classhierarchy
