### ISSUE TITLE
Mitral regurgitation is not necessarily morphological

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#1438] opened 2017-03-15 17:58 UTC
currently:

     is_a HP:0001627 ! Abnormal heart morphology
      is_a HP:0001654 ! Abnormality of the heart valves
       is_a HP:0006705 ! Abnormality of the atrioventricular valves
        is_a HP:0001633 ! Abnormality of the mitral valve
         is_a HP:0001653 ! Mitral regurgitation 

We think we need to distinguish structural/morphological vs functional

**Comment by pnrobinson** [comment] 2017-09-18 01:43
@cmungall @drseb @mellybelly Ihave added morphologic vs physiologic to abnormality of the mitral valve. Iagree that mitral regurgitation is functional (and the causes of the regurgitation may be morphological and can be coded separately). We will need to alter the logical definitions (also for tricuspid). I am closing this issue because it is duplicated in #2205

**Closed by pnrobinson** 2017-09-18 01:43 UTC
