### ISSUE TITLE
Obsolete Autistic Behavior

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#9587] opened 2023-01-19 03:39 UTC
**HPO term**
Autistic behavior

**Reason for deprecation**
This term categorizes a complex combination of phenotypic features which are poorly defined. Many behaviors are related to the diagnosis of ASD, but these behaviors are not all closely related when using HPO's is_a relationship.

**Suggested replacement or term to consider**
Abnormal social behavior (HP:0012433)

**Comment by pnrobinson** [comment] 2023-01-19 07:36
I do not think we can obsolete this term because so much of the genetics literature uses it, and we would lose information if we replace it with a more generic term. Perhaps it is best to supply a warning that more detailed phenoptyping is desirable and that this term should not be used moving forward. This would be a good topic for the upcoming NIMH meeting!

**Comment by bcoleman96** [comment] 2023-01-20 16:06
I agree. Although I could see something like this being a time suck for the workshop. If we want to address it at the meeting, I think we should come up with a concise solution first. Otherwise, maybe we could revisit it after the workshop and see if a good replacement term has appeared.

**Comment by pnrobinson** [comment] 2023-01-25 10:11
The problem is that we have 557 diseases annotated to this term
https://hpo.jax.org/app/browse/term/HP:0000729
and for the most part, the original literature just says something like "autistic behavior" or "autistic features", and so if we obsolete this term, we lose a lot of information about these diseases.

**Comment by pnrobinson** [comment] 2023-07-15 22:49
@bcoleman96  There is no way we can obsolete this term given the legacy of annotations. Closing for now. We need to add some statement about annotations for new data moving forward.

**Closed by pnrobinson** 2023-07-15 22:49 UTC
Labels: obsoletion
