### ISSUE TITLE
Susceptibility to loci in OMIM should be moved from MONDO to HPO annotations

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#3302] opened 2017-12-09 05:53 UTC
These are really association data and not diseases and should not be in MONDO or HPO but rather our annotation files. For example, 

https://omim.org/entry/608446 Myocardial infarction, susceptibility to

We could just create a separate annotation file for these?

**Comment by pnrobinson** [comment] 2017-12-09 12:19
The issue is that these loci are not different except perhaps in effect size from the loci noted in GWAS central. We need to set up a plan for annotating common disease like this. I have a proposal for a file format that we can discuss in Portland -- once we settle on that, let us extend PhenoteFX for that format and then let's do a deep dive on a few diseases to get the hang of things! But this is feasible and we need to start now!

**Comment by pnrobinson** [comment] 2018-05-07 10:39
I am going to close this issue, because we are working on the omit-list.txt file to do just this.

**Closed** 2018-05-07 10:39 UTC
