### ISSUE TITLE
Reduced progressive sperm motility 

### ISSUE THREAD

**Issue by MagoWyr** [obophenotype/human-phenotype-ontology#9828] opened 2023-06-16 10:10 UTC
**HPO term**
HP:0034011

**Reason for deprecation**
Motility is sperm is only measured for progressive sperm. If progressive motility is reduced the phenotype is represented by the term "Reduced sperm motility (HP:0012207)".

**Suggested replacement or term to consider**

**Comment by pnrobinson** [comment] 2023-06-17 20:31
It does seem that both motility and progressive motility are reported separately, e.g., "Sperm motility and progressive motility were dramatically decreased in these individuals with SSX1 variants" (see https://pubmed.ncbi.nlm.nih.gov/36796361/). I am concerned that if we conflate the two that existing annotations will be invalidated -- thoughts?

**Comment by MagoWyr** [comment] 2023-06-18 11:40
The current standard by the WHO (lab manual page 3) is the following one:

"Assessment of sperm motility. The categorization of sperm motility has reverted
back to fast progressively motile, slow progressively motile, non-progressively
motile and immotile (grade a, b, c or d) because presence (or absence) of rapid
progressive spermatozoa is clinically important"

According to this categorisation there is no measurement or reporting of spermatozoa which are motile but not progressively motile, i.e. only the progression is counted as being motile.

**Comment by pnrobinson** [comment] 2023-07-01 12:04
The issue is that reduced motility is a phenotypic abnormality that has been reported in many diseases, and I do not think the WHO statement is explicitly stating that this is an invalid observation? Many articles in the human genetics literature report both phenotypes and so I would prefer to retain the term unless it is outright wrong.
The other question would be whether  [Abnormal sperm motility HP:0012206](https://hpo.jax.org/app/browse/term/HP:0012206)  needs an addition term "Absent progressive sperm motility (syn: non-progressively
motile sperm)?

**Comment by MagoWyr** [comment] 2023-07-03 08:44
Okay, we can retain the term. But I don't think that Abnormal sperm motility needs the proposed addition term.
________________________________

**Comment by pnrobinson** [comment] 2023-07-16 13:09
OK, will not add the additional term, thanks!

**Closed by pnrobinson** 2023-07-16 13:09 UTC
Labels: obsoletion
