### ISSUE TITLE
Terms with multiple comments?

### ISSUE THREAD

**Issue by sdumitriu** [obophenotype/human-phenotype-ontology#4820] opened 2019-05-02 17:02 UTC
**HPO term**

HP:0002282
HP:0032497

**Bug description**

In the April release there are two terms with multiple `comment` fields: `HP:0002282` and `HP:0032497`. This seems new in this release, our assumption so far has been that only one comment per term is allowed. Is this an error in the release, or should we change our assumption to support fields with multiple comments?

**Comment by drseb** [comment] 2019-05-02 17:22
Thanks. Duplicate of https://github.com/obophenotype/human-phenotype-ontology/issues/4817

**Closed by drseb** 2019-05-02 17:22 UTC
Labels: bug, typo
