### ISSUE TITLE
new term:Cornea verticillata?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1460] opened 2017-03-21 10:22 UTC

**Comment by pnrobinson** [comment] 2017-04-19 18:42
Def: Golden brown or gray deposits with a clockwise, whorl-like distribution in the inferior interpalpebal portion of the cornea.
synonym (exact): Vortex keratopathy
comment: Cornea verticillata may occur due to Fabry disease and as an adverse effect to medications including amiodarone.


synonym: Vortex keratopathy

**Comment by LCCarmody** [comment] 2017-04-24 19:55
Duplicate of cornea verticillata #2183

**Closed by LCCarmody** 2017-04-24 19:55 UTC
Labels: new term request
