### ISSUE TITLE
Consider making 'Inability to walk' a subclass of 'Difficulty walking'

### ISSUE THREAD

**Issue by allenbaron** [obophenotype/human-phenotype-ontology#10154] opened 2023-10-05 22:57 UTC
**HPO term**
HP:0002355 - Difficulty walking
HP:0002540 - Inability to walk

**Suggested revision and reasons**
Both are children of 'Gait disturbance' (HP:0001288) and seem to differ primarily by degree, i.e. inability to walk is an extreme version of walking difficulty.

Note that 'Difficulty walking' is a child of the undefined term 'Functional motor deficit', while 'Inability to walk' is not but I don't think that precludes this change.

**Comment by pnrobinson** [comment] 2023-12-14 12:02
@allenbaron  Not sure I understand the suggestion!

**Comment by pnrobinson** [comment] 2024-01-25 08:27
@allenbaron 
Looking at this, I wonder if Difficulty walking and Gait disturbance are actually synonyms, I think we should merge the two terms.

**Comment by allenbaron** [comment] 2024-01-25 13:53
My wife as a PT generally considers them different things. There are gait disturbances that don't result in any functional difficulty walking. But based on how gait disturbance is currently defined in HP I think they could very well be considered synonyms. In fact, I'd even say that the definition for difficulty walking is broader than the one for gait disturbance, since that definition states that gait disturbance is a subset of difficulty walking caused by neuro/muscle diseases.

My original thought was that inability to walk could be a child of difficulty walking, based on the idea that the inabiliity is essentially having an extreme difficulty. If the difficulty walking and gait disturbance terms are merged it would have the same practical effect as my original suggestion.

One lingering question is what to do about the organization of difficulty walking under functional motor deficit? I can imagine a scenario where difficulty walking and inability to walk are considered functional motor deficits and not gait disturbances. I think this is how my PT wife sees them. I think either approach could be right, depending on how HP is trying to model these different things.

**Comment by pnrobinson** [comment] 2024-07-06 10:19
Thanks for the detailed comments. The problem is that phrases like this are used with different "latent" meanings in the literature. There are also concepts that we are trying to model. Finally, the definitions that the HPO has developed over the years sometimes need improvement. In general, we try to avoid encoding etiology and so it is probably good to remove the bit about "caused by neuro/muscle diseases" from the definition. 

In any case, I would suggest that we merge "Difficulty walking" with "Gait disturbance" because a subterm in an ontology should be defined like this:

"Difficulty walking" is a type of "Gait disturbance" that is delineated from "Gait disturbance" and from other subtypes of "Gait disturbance" by XZY.
I do not think that "Difficulty walking" has anything specific about it that would allow us to write a definition like that.
Thoughts?

**Comment by allenbaron** [comment] 2024-07-09 14:27
I think it makes sense to remove the etiology portion from the definition of "gait disturbance". I also don't see a practical reason to keep "difficulty walking" and agree that it's reasonable to merge these two terms.

The only caveat I see is in the semantics of "difficulty" versus "disturbance" but it seems like complete agreement would be difficult to achieve and that it's a reasonable conflation that most people would understand.

**Comment by pnrobinson** [comment] 2024-07-14 08:01
@allenbaron thanks!
I have merged "Difficulty walking" into Gait disturbance, and moved and revised part of the definition to be the following comment:
Gait disturbances can be caused by neurological or muscular diseases but also fractures or other sources of pain that is triggered upon walking.

**Closed by pnrobinson** 2024-07-14 08:01 UTC
Labels: hpo-classhierarchy
