### ISSUE TITLE
new term:Whipple's triad ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2145] opened 2017-03-21 13:54 UTC

**Comment by LCCarmody** [comment] 2017-03-31 19:33
@pnrobinson This is the definition I found: Whipple triad is the clinical presentation of pancreatic insulinomas and consists of: fasting hypoglycemia (<50 mg/dl) symptoms of hypoglycemia. immediate relief of symptoms after the administration of IV glucose.

This appears to be a clinical finding, but not sure if it is a phenotype.

**Comment by pnrobinson** [comment] 2017-04-08 13:29
The HPO strives to provide terms for "atomic" (individual, specific) phenotypes. Whipple's triad is a "bundled" collection of several items and also is not really well defined (the first criteria is Symptoms known or likely to be caused by hypoglycemia especially after fasting or heavy exercise according to wikipedia). I think the HPO does need a term, fasting hypoglycemia.

**Comment by LCCarmody** [comment] 2017-04-11 20:00
There is already a term "Fasting hypoglycemia" HP_0003162.

**Comment by pnrobinson** [comment] 2017-04-18 15:10
Thanks -- then I am closing this request.

**Closed by pnrobinson** 2017-04-18 15:10 UTC
Labels: new term request
