### ISSUE TITLE
BRCA1 and BRCA2 missing/incorrect

### ISSUE THREAD

**Issue by diannafisk** [obophenotype/human-phenotype-ontology#524] opened 2015-10-22 19:45 UTC
HP:0003002 (Breast Carcinoma) is not currently associated with BRCA1 or BRCA2, the two genes associated with the majority of familial breast and ovarian cancer.

HP:0003002 (Breast Carcinoma) IS correctly associated with OMIM:612555 (BREAST-OVARIAN CANCER, FAMILIAL, SUSCEPTIBILITY TO, 2) and OMIM:604370 (BREAST-OVARIAN CANCER, FAMILIAL, SUSCEPTIBILITY TO, 1) but those diseases not associated with any genes;  the correct associations are OMIM:612555=BRCA2 and OMIM:604370=BRCA1.

These associations are missing from both the HPO browser and the disease-gene-phenotype files.

Please add!  

(I'm also curious as to how these associations were dropped or missed in the parsing of OMIM data)

Thanks!

-Dianna

**Comment by drseb** [comment] 2015-11-24 16:41
Thanks.

We only take true disease-to-gene associations currently. The entries you mention [indicate mutations that contribute to susceptibility to multifactorial disorders](http://www.omim.org/help/faq). So this is not a bug and intended behaviour. We might change our strategy somewhen in the future.

**Comment by pnrobinson** [comment] 2015-11-24 19:25
This is a difficult question, and I think that current databases do not do a great job of modeling these diseases. Familial cancer is susceptibility to cancer (i.e., if you are a woman and have a pathogenic BRCA1 mutation, your chance of getting breast cancer by the age of 60 years might be 80%). However, the susceptibility is transmitted in a Mendelian fashion, and the degree of increased risk is substantial. This is in contrast to diseases such as schizophrenia, in which there are hundreds of different susceptibility alleles, and the transmission of the overall susceptibility is NOT Mendelian. Therefore, I think that the diseases that OMIM marks as cancer susceptibility are actually Mendelian diseases and that we should basically be using two labels for these two very different kinds of diseases. I think that we should have OMIM:612555=BRCA2 and OMIM:604370=BRCA1 etc. in our database, let us discuss this!
-Peter

**Comment by drseb** [comment] 2015-11-29 11:45
I moved this ticket to a more appropriate repository and will close this issue here.

**Closed by drseb** 2015-11-29 11:45 UTC
