### ISSUE TITLE
new term:Drug taking?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2114] opened 2017-03-21 13:51 UTC
Term that could be classified in a group called triggering factors in clinical modifiers?

**Comment by pnrobinson** [comment] 2017-06-18 19:16
@LOURGHI I am not sure this is a great term -- can you provide us with more details? Also remember that if the cause of say psychosis is drug taking, then we would model the drug taking as the cause of the disease rather than something that led to a complication of another disorder (the use case of the triggered by terms is to indicate that a given HPO term that characterizes a disease is triggered by something -- it is not meant to be used to describe the underlying etiology of a disease).
I am going to close this now, but if there is an indication like the above, please reopen with more details.

**Closed by pnrobinson** 2017-06-18 19:16 UTC
Labels: new term request
