### ISSUE TITLE
postsurgical pheontypes?

### ISSUE THREAD

**Issue by daboe01** [obophenotype/human-phenotype-ontology#2184] opened 2017-04-21 10:29 UTC
may i suggest terms for phenotypes induced by surgical interventions (corneal transplantation)?
what about phenotypes induced from grafting complications (e.g. graft rejections)?

**Comment by pnrobinson** [comment] 2017-04-21 11:28
Sure, any of this is in scope. We would be looking for terms that describe the actual phenotypes and not (say) "posttransplant keratopathy". Do you have suggestions or good references?

**Comment by daboe01** [comment] 2017-04-27 10:57
here are my suggestions for ophthalmology:

presence of a full-thickness corneal graft
presence of a lamellar endothelial/stromal graft
presence of an endothelial graft
presence of a stromal graft
presence of an amniotic membrane graft

**Comment by pnrobinson** [comment] 2017-04-28 10:20
Thank you -- the scope of the HPO has been to have terms for abnormal phenotypes caused by diseases. The above items are phenotypes that are caused by the treatment of the disease, and I believe they are wished-for features rather than being regarded as abnormal. It is possible that we will begin modelling items like this in future years, but this would be a major undertaking that would require a lot of thought and funding. I will close this issue for now but please reopenif I have misunderstood.

**Closed by pnrobinson** 2017-04-28 10:20 UTC

**Comment by daboe01** [comment] 2017-04-28 10:55
i see your point. however, my idea was to code e.g. posttransplant keratopathy (punctate keratitis of the graft) by means of assigning the new term of "presence of a full-thickness corneal graft" together with the established term for punctate keratitis.

**Comment by daboe01** [comment] 2017-04-28 11:02
could you alternatively introduce some kind of modifiers to flag the posttransplant phenotypes?

**Comment by pnrobinson** [comment] 2017-04-28 11:09
The issue is that if we started to do this we would want to add coverage for all medical disciplines and set up algorithms to compute over it and we do not have the bandwidth at the present time. The HPO is planning on doing much more with common complex disease (the initial focus was on rare disease), but there are many issues that need to be sorted out to get everything to work well together. I think that in maybe 1-2 years we will be in a position to think about how to do this kind of modelling.

**Comment by pnrobinson** [comment] 2017-04-28 11:11
Refering to your comment further above ( posttransplant keratopathy ), I understand better what you mean. It might be good to set up a telcon to discuss the use case and goals. If you like send me an email at peter.robinson@jax.org

**Comment by callahantiff** [comment] 2019-03-04 17:33
I wanted to follow-up and see if progress was made with respect to this request for new terms? If this avenue is being pursued, I'm happy to help.
