### ISSUE TITLE
Build fails when I try to add a comment to 'Severe T-cell immunodeficiency'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3345] opened 2018-01-12 00:51 UTC
I tried to add the comment below to 'Severe T-cell immunodeficiency' in Protege, using the rdfs:comment annotation, and when I do, it breaks the build. Is this the wrong annotation?

Several diseases are classified as severe T cell immunodeficiencies: severe combined immunodeficiency syndrome (SCID), reticular dysgenesis, thymic dysplasia (Nezelof’s syndrome), combined immunodeficiency disease (CID), and Wiskott–Aldrich syndrome (WAS).

**Comment by pnrobinson** [comment] 2018-01-12 01:12
Did you check if the "-" is OK? This is a common cause of coding errors ("-" vs "-" the latter of which I just typed on my linux keyboard).

-Peter



Peter Robinson

Professor and Donald A. Roux Chair, Genomics and Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

New Book: Computational Exome and Genome Analysis<https://www.crcpress.com/Computational-Exome-and-Genome-Analysis/Robinson-Piro-Jager/p/book/9781498775984>

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by nicolevasilevsky** [comment] 2018-01-12 01:13
that very well could be the problem! Thanks Peter!

**Comment by nicolevasilevsky** [comment] 2018-01-12 16:48
I tried removing the dash and it still fails, not sure what the issue is! Not sure how critical it is to have this comment, but maybe @pnrobinson, you would like to try to add it next time you are editing?

**Comment by pnrobinson** [comment] 2018-01-14 16:51
I have added the comment. It seems to parse OK, and it is not the cause of the ontolib error I am having. Therefore, I will close this issue.

**Closed by pnrobinson** 2018-01-14 16:51 UTC
