### ISSUE TITLE
issues with senile macular degeneration

### ISSUE THREAD

**Issue by daboe01** [obophenotype/human-phenotype-ontology#2192] opened 2017-04-28 13:06 UTC
i understand that HPO does not code diagnoses.
however, you included age related macular degeneration (7868)
the relevant pheontypes are also there: drusen (30499) and atrophy (7791) for try AMD and  choroidal neovascularisation (11506) for wet AMD.
i would suggest to add an is_a relation for the aforementioned pheontypes to HPO term 7868

**Comment by pnrobinson** [comment] 2017-04-28 16:30
This is correct. The reason for this is that sometimes entities like macular degeneration are regarded as phenotypic features of other diseases (e.g., hereditary neuropathy with or without age-related macular degeneration caused by mutation in FBLN5). This means that we have descriptions of the FBLN5 disease that say "macular degeneration" but do not mention the actually observed phenotypes that led to that conclusion. This is a difficult question that is related to the philosophical definition/model of diseases. We would like to extend our current data structures to allow a more sophisticated way of interrelating diseases and phenotypes, but it is a substantial project that will require a lot of new computer code etc.

It is not correct to say that drusen is_a macular degeneration because as far as the computer is concerned, this has to be always true (but there are other diseases that cause drusen). So, these are excellent suggestions, and I agree completely. But we need to do a lot of work on our side to implement them and still make sure all of the HPO software still works as intended. 

I will close this item right now, but say that I hope we will have prototypes of a more flexible system by the end of the year.

**Comment by daboe01** [comment] 2017-04-28 19:11
ok, i see.
however, (at least by the common definition) _age related_ macular generation cannot be a feature of other diseases. As the name says, it is related to age and not to other conditions. Here you use different terms, such as juvenile macular degeneration.

**Comment by pnrobinson** [comment] 2017-04-28 19:19
@LCCarmody @mellybelly @drseb 
daboe01 is making a very valid point, and I think we should revisit this topic. For instance, if a disease is now annotated to juvenile macular degeneration, then we can re-annotated to macular degeneration with an onset modifier. Let us re-examine our files.

**Comment by drseb** [comment] 2017-05-02 08:16
@pnrobinson can you reformulate the problem for me again?

What are the steps to solve the problem? (Sorry, I can't follow completely)

**Comment by pnrobinson** [comment] 2018-07-02 11:23
Currenty, Age-related macular degeneration is being used only to describe phenotypes of the OMIM entries for ARMD:
https://hpo.jax.org/app/browse/term/HP:0007868
This does not make a lot of sense, and I am going to implement @daboe01 suggestion that we reannotate those diseases with the actual phenotypic features of ARMD.

**Comment by pnrobinson** [comment] 2018-07-02 11:29
https://www.nhs.uk/conditions/age-related-macular-degeneration-amd/symptoms/
* a blurred or distorted area in your vision

    seeing straight lines as wavy or crooked
    objects looking smaller than normal
    colours seeming less bright than they used to
    seeing things that aren't there (hallucinations)

also 
Visual impairment
Geographic atrophy
Constricted central visual field

Currently, we do not distinguish between wet and dry ARMD -- we need to do so in MONDO @cmungall @nicolevasilevsky these would be good examples for the new annotation format

**Comment by pnrobinson** [comment] 2018-07-09 00:37
I have updated the annotations and am obsoleting (merging) this term, which refers to a disease not a phenotype. I have annotated to macular degeneration Onset "Late".

**Closed** 2018-07-09 00:38 UTC
